import { Inter } from "next/font/google";
import "./globals.css";
import GlobalState from "@/context";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E Commerce Website App",
  description: "Generated by Alejandro Barreto",
};

/**
 * RootLayout component
 * @param {JSX.Element} children 
 * @returns {JSX.Element}
 */
export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <GlobalState>
          <Navbar />
          <main> {children} </main>
        </GlobalState>
      </body>
    </html>
  );
}
